sudo: required  
dist: trusty
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.5"
  - "4.4"
before_script:
  - npm install

after_script: cat ./coverage/**/lcov.info | ./node_modules/.bin/coveralls